### ISSUE TITLE
pip.operations import is out of date

### ISSUE THREAD

**Issue by laylasells** [dmahugh/dougerino#1]
Since version 10 there is a new way to install it so the following is recommend: 
try:
    from pip._internal.operations import freeze
except ImportError:
    from pip.operations import freeze

**Comment by dmahugh** [comment]
Thanks, I refactored some things and eliminated the need for freeze. Fixed in [various fixes for latest Python/pip versions](https://github.com/dmahugh/dougerino/commit/b2ad329c74a38aca92fbb65c9827730dcd142fb2).

**Comment by laylasells** [comment]
Wow, that was fast.  I have pyfind working on my machine now.  Thanks!
________________________________
